version: "3.9"

services:
  sandstorm-server:
    image: rouhim/insurgency-sandstorm-server
    build:
      context: .
    env_file:
      - .env
    ports:
      - 27102:27102/tcp
      - 27102:27102/udp
      - 27131:27131/tcp
      - 27131:27131/udp
    logging:
      driver: "json-file"
      options:
        max-size: "50m"