version: "3.9"

services:
  server:
    image: rouhim/insurgency-sandstorm-server
    build:
      context: .
    env_file:
      - .env
    #volumes:
    #  - ./ini-config:/sandstorm/Insurgency/Saved/Config/LinuxServer:ro # Engine.ini, Game.ini
    #  - ./txt-config:/sandstorm/Insurgency/Config/Server:ro # Admin.txt, Mods.txt, Motd.txt
    #  - ./Mods:/sandstorm/Insurgency/Mods:rw
    ports:
      - 27102:27102/tcp
      - 27102:27102/udp
      - 27131:27131/tcp
      - 27131:27131/udp
    logging:
      driver: "json-file"
      options:
        max-size: "50m"